### ISSUE TITLE
Проблема с запуском

### ISSUE THREAD

**Issue by Klatch13** [27rogi/Fabric2Discord#4]
Я не могу запустить сервер с этим модом, нужны какие то дополнительные моды?

**Comment by Seercat3160** [comment]
Could you post your latest.log when this occurs (using something like [mclo.gs](mclo.gs))

**Comment by Tysmithyyy** [comment]
[2022-07-31-4.log.gz](https://github.com/rogi27/Fabric2Discord/files/9228181/2022-07-31-4.log.gz)
I am getting this error when trying to start on a 1.19.1 fabric server.

**Comment by Seercat3160** [comment]
@Tysmithyyy it seems that Fabric2Discord's `ServerPlayNetworkHandlerMixin` mixin is not compatible with something in the user's server environment (potentially 1.19.1 itself), so the mod might have to be updated for this version. Also, please create a new issue for new support requests rather than piggybacking on an existing issue to notify those already working there.

**Comment by 27rogi** [comment]
> @Tysmithyyy it seems that Fabric2Discord's `ServerPlayNetworkHandlerMixin` mixin is not compatible with 1.19.1, so the mod will have to be updated for this version. Also, please create a new issue for new support requests rather than piggybacking on an existing issue to notify those already working there.

Many thanks for helping with this issue, I will try to fix it.

**Comment by Tysmithyyy** [comment]
My bad for not creating a new issue. Thanks for looking into it guys. Looking forward to using the mod.

**Comment by 27rogi** [comment]
Should be resolved.
